name: Deploy to Firebase
on:
  release:
    types: [created]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      - run: .github/bin/build.sh

      - uses: SonarSource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4 # v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - run: .github/bin/qlty-coverage-publish.sh
        env:
          QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
      - run: npm install -g firebase-tools
      - shell: bash
        env:
          CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
        run: echo "$CREDENTIALS_BASE64" | base64 --decode > credentials.json
      - run: echo "GOOGLE_APPLICATION_CREDENTIALS=./credentials.json" >> $GITHUB_ENV
      - shell: bash
        run: firebase deploy --non-interactive
      - run: rm credentials.json
